name: Publish Package

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: read

  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"

      - run: npm install --ignore-scripts

      - run: npx husky install

      - run: npm run build

      - run: npm publish --provenance --access public
